name: ESP32 OTA Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Purge build artifacts
      run: |
        rm -rf build sdkconfig sdkconfig.old

    - name: Setup ESP-IDF
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.1
        target: esp32c3

    - name: Build project
      run: |
        idf.py set-target esp32c3
        idf.py fullclean
        idf.py build

    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: build/firmware.bin