name: ESP32 Firmware Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        target: [esp32c3]
        include:
          - target: esp32c3
            build_dir: build-esp32c3
            
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup ESP-IDF
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.1
        target: ${{ matrix.target }}

    - name: Build project
      run: |
        idf.py set-target ${{ matrix.target }}
        idf.py build
        mv build ${{ matrix.build_dir }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: firmware-${{ matrix.target }}
        path: |
          ${{ matrix.build_dir }}/firmware.bin
          ${{ matrix.build_dir }}/partition_table/partition-table.bin
          ${{ matrix.build_dir }}/bootloader/bootloader.bin

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: firmware-*
        path: artifacts
        merge-multiple: true

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        files: |
          artifacts/**/*.bin