name: ESP32 OTA Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        path: src

    - name: Setup ESP-IDF
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.1
        target: esp32c3
        working-directory: src
    - name: Clean build artifacts
      run: |
        cd src
        idf.py fullclean  # Полная очистка предыдущих сборок

    - name: Build project
      run: |
        cd src
        idf.py build

    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: src/build/firmware.bin

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: firmware
        path: artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        files: |
          artifacts/firmware.bin