name: ESP32 OTA Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set config
      run: |
        echo "CONFIG_EXAMPLE_WIFI_SSID=\"${{ secrets.WIFI_SSID}}\"" > sdkconfig.local
        echo "CONFIG_EXAMPLE_WIFI_PASSWORD=\"${{ secrets.WIFI_PASS}}\"" >> sdkconfig.local
        echo "CONFIG_OTA_UPDATE_URL=\"${{ secrets.OTA_URL}}\"" >> sdkconfig.local

    - name: Setup ESP-IDF
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.1.0
        target: esp32c3

    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: build/esp_ota2.bin

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: firmware

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        files: |
          esp_ota2.bin