name: ESP32 OTA Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup ESP-IDF
      uses: espressif/esp-idf-ci-action@v2
      with:
        esp_idf_version: v5.1
        target: esp32c3

    - name: Build project
      run: |
        idf.py build

    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: build/firmware.bin

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: firmware

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        files: |
          firmware.bin
